### ISSUE TITLE
yande.re listing doesn't work

### ISSUE THREAD

**Issue by z0rc** [flexbooru/flexbooru#104]
**Describe the bug**
Added yande.re as Danbooru 1.x server. Seems account login works as I can add own account and it shows account ID, but posts listing throws exception.

**To Reproduce**
1. Add yande.re as Danbooru 1.x server (see screenshot)
2. Login into account
3. Open Posts listing
4. Observe the error

**Expected behavior**
Posts listing should load images.

**Screenshots**
![image](https://user-images.githubusercontent.com/787519/67642248-750ca000-f912-11e9-9ebe-d12d178f1c4d.png)
![image](https://user-images.githubusercontent.com/787519/67642244-6f16bf00-f912-11e9-8f48-9aa6b0d78b25.png)

**Device (please complete the following information):**
 - Device name: OnePlus 5T
 - OS version: Android 9.0
 - App version: 1.1.10.c874 installed from Google Play Store

**Comment by onlymash** [comment]
https://flexbooru.github.io/flexbooru/config.html

**Comment by z0rc** [comment]
Thanks, I searched prior to submitting this bug, but didn't came across this link. Consider issue resolved.

Still it would be better if this link was discoverable from within app, rather than searching web, or trying to guess configuration on your own.

**Comment by EarsKilla** [comment]
![Screenshot_20191109-071111](https://user-images.githubusercontent.com/17800772/68522768-44d4e200-02c0-11ea-8bf7-20a58a9ae96b.jpg)

config from URL given by @onlymash works fine for me. try to use VPN or Orbot (tor).
