### ISSUE TITLE
Player audio playing in background even after you swipe

### ISSUE THREAD

**Issue by hunterx9** [flexbooru/flexbooru#107]
When browse activity displays posts, if its a video and is playing and you swipe to another post, the audio is still playing in the background. So, background audio plays until you have another video post.

**To Reproduce**
1. Search for  'animated'
2. If the post is video with audio let it play while buffering
3. Swipe left or right; the swiped post should be picture/gif
4. Audio will be played in the background

**Device:**
 - Device name: [Samsung M20]
 - OS version: [Pie]

**Comment by onlymash** [comment]
Fix by v2.2.2
