### ISSUE TITLE
Chan.sankakucomplex.com

### ISSUE THREAD

**Issue by pervertkirito** [flexbooru/flexbooru#108]
sankakucomplex website change something again causes flexbooru on popular tab to no longer showing rest of the results.

also posts now showing comics even though nothing wrong show up on chrome

**Comment by hunterx9** [comment]
popular tab is working fine. posts showing comics in sankaku is common place filter order:recently_voted or something. do not put tag blacklist to doujinshi though something breaks and it does not load posts, i m looking into the issue but havent found a fix

**Comment by retardedloozer** [comment]
How do you add Sankaku Complex? I can't do that

**Comment by hunterx9** [comment]
https://flexbooru.github.io/flexbooru/config.html
