### ISSUE TITLE
Crash on my smartphone

### ISSUE THREAD

**Issue by AmemiyaAkira** [flexbooru/flexbooru#111]
**Describe the bug**
When I launch Flexbooru, it crashes down. Whether I use VPN or not.

**To Reproduce**
1. Luanch Flexbooru
2. Add danbooru
3. Click on danbooru
4. Crash down, and create a *.log file

**Expected behavior**
Run Flexbooru without crashes.

**Device (please complete the following information):**
 - Device name: [Xiaomi 9 SE]
 - OS version: [MIUI 11.0.5, Android 9]
 - App version: [1.1.10.c874]

**Additional context**
This is the file mentioned above.
[crash-2020-02-19-13-29-00-1582090140157.log](https://github.com/flexbooru/flexbooru/files/4223291/crash-2020-02-19-13-29-00-1582090140157.log)

**Comment by onlymash** [comment]
Danbooru API field is changed. I am fixing it.

If danbooru keep crashing, disconnect the network, then switch to another booru.

**Comment by onlymash** [comment]
Wait next update

**Comment by AmemiyaAkira** [comment]
> Danbooru API field is changed. I am fixing it.
> 
> If danbooru keep crashing, disconnect the network, then switch to another booru.

I can use konachan and yande.re properly, thanks. I'm looking forward to next update.

**Comment by onlymash** [comment]
Fix by https://github.com/flexbooru/flexbooru/commit/7c84b0d99c3cac5f9a07ec0fa09de7cce4a5e0ee
