### ISSUE TITLE
Blurry image previews in Danbooru.

### ISSUE THREAD

**Issue by Kazarlx** [flexbooru/flexbooru#113]
When I'm looking for something in Danbooru, the image previews are blurry, wheras they're not in the website. It's a subtle detail but it's really annoying.

Here's a screenshot to show you what I mean:
![Screenshot_20200223-050703_Flexbooru](https://user-images.githubusercontent.com/61369826/75103594-ee847880-55fc-11ea-88e5-3cf866a3b46d.jpg)
Please fix it :)

**Comment by onlymash** [comment]
https://danbooru.donmai.us/posts.json?limit=1
This depends on the files provided by the API, the ```preview_file_url``` itself is small.

**Comment by fredgido** [comment]
could you lazy load large_file_url over the thumbs after the thumbs are loaded?
over wifi only
