### ISSUE TITLE
At most 3 booru websites can be shown

### ISSUE THREAD

**Issue by LittleYe233** [flexbooru/flexbooru#117]
I have added 4 booru websites in correct settings, but there are only 3 websites that can be chosen. The fourth website is not shown and I can't go through its pictures. Restarting the software and the smartphone is tried and nothing goes well. Is it a bug?

**Comment by onlymash** [comment]
![17088](https://user-images.githubusercontent.com/5838634/75313197-1a228f80-5897-11ea-9f0a-c5e86b9d53e1.png)

**Comment by LittleYe233** [comment]
Σ( ° △ °|||)︴Well, maybe I have some eye problems... Thanks for your answer!
