### ISSUE TITLE
Crashing when activating explicit content

### ISSUE THREAD

**Issue by yoshnopa** [flexbooru/flexbooru#119]
Whenever I activate the showing of explicit content in a Danbooru while logged in crashes the app.
Crasging means directly on start, making usage impossible and resetting only available by completely reinstalling.
Interestingly enough, this seems to be dependent on the order this is done in: When turning off safe mode first, this bug does not occur. However, when first the account is set, and then the safe mode deactivated, this happens.

**Comment by yoshnopa** [comment]
Found out why, its because of the change of api in danbooru. The old standard can now obviously cause error, which means the booru has to be on the most current version. Whether there should be a legacy support for danbooru is not really something I can judge, if this is nothing of interest this can be closed.

**Comment by onlymash** [comment]
I'm refactoring the data layer (almost completely rewritten again, greatly simplifying the code), so I won't solve the problems with the current version

**Comment by onlymash** [comment]
Fixed by v2.0
