### ISSUE TITLE
e621.net/e926.net issues

### ISSUE THREAD

**Issue by duvjones** [flexbooru/flexbooru#120]
So I was wondering if it was noted that e621/e926 [API](https://e621.net/help/api)  has changed and flexbooru no longer works with those sites.

**Comment by onlymash** [comment]
fixed by v2.0.x

**Comment by duvjones** [comment]
Thank you, that is helpful. 

Alas, I don't think that we are done here. After that update, I have been finding that I can't log into my account on either site, the API key is correct on both, and any attempt gives me a error code: 403
Despite the browser on my phone loading up the site fine.

**Comment by onlymash** [comment]
Its e621's bug
You can compare the two differences:

https://danbooru.donmai.us/users.json?search[name]=username
.
https://e621.net/users.json?search[name]=username

**Comment by onlymash** [comment]
Even if the user check is ignored, the favorite api cannot be used, they destroyed the original Danbooru api
