### ISSUE TITLE
safebooru.org preview image does not display properly

### ISSUE THREAD

**Issue by AhRoon** [flexbooru/flexbooru#152]
**Describe the bug**
safebooru.org preview image does not display properly. 

**To Reproduce**
1. Create booru config with Gelbooru, safebooru.org.
2. Save and select the safebooru.org config.
4. Preview image does not display properly.

**Expected behavior**
Preview does not display properly. 

**Screenshots**
![Screenshot_20200611-082317_Flexbooru](https://user-images.githubusercontent.com/25527589/84328453-f6245900-abbc-11ea-8ccb-c9459fd101e4.jpg)
![Screenshot_20200611-081508_Flexbooru](https://user-images.githubusercontent.com/25527589/84328458-f91f4980-abbc-11ea-8446-de7b9c54de40.jpg)

**Device (please complete the following information):**
 - Device name: Samsung Galaxy S20
 - OS version: Android 10
 - App version: 2.5.1.c1137

**Additional context**
Strangely, safebooru.org from web browser works fine, it only happens to Flexbooru.

**Comment by onlymash** [comment]
![Screenshot_20200611-073145](https://user-images.githubusercontent.com/5838634/84328837-b27a2100-abb5-11ea-9374-c6b13009e761.png)
![Screenshot_20200611-073140](https://user-images.githubusercontent.com/5838634/84328843-b3ab4e00-abb5-11ea-86b6-204b73cf3bfa.png)

**Comment by onlymash** [comment]
Contact the webmaster to fix the picture link
