### ISSUE TITLE
Can't view explicit/questionable images.

### ISSUE THREAD

**Issue by thesadru** [flexbooru/flexbooru#157]
**Describe the bug**
All searches and the default page show only safe results. When I try to select a certain rating, all results for explicit/questionable images return an empty board.

**To Reproduce**
This just might be a problem on my side
0. Download app
1. Open any board
2. Search `rating:explicit`

**Expected behavior**
Explicit results should be returned.

**Screenshots**
[Search result](https://user-images.githubusercontent.com/58166507/98543683-228af100-2293-11eb-9776-021da739a28b.jpg)

**Device (please complete the following information):**
 - Device name: Redmi 7A
 - OS version: Android 9
 - App version: 2.6.1.c1151

**Additional context**
I have redownload the app and the problem resigns.

**Comment by onlymash** [comment]
Disable safe mode
