### ISSUE TITLE
sankaku won't work

### ISSUE THREAD

**Issue by tuper579** [flexbooru/flexbooru#159]
error code:500

**Comment by chaoskagami** [comment]
They're blocking the user agent like they did to imgbrd-grabber, since Flexbooru identifies itself deliberately. Modifying the user agent to a generic firefox one seems to fix the issue mostly.

**Comment by nagaisa** [comment]
i am geting the same error. any fix so far?

**Comment by tuper579** [comment]
> i am geting the same error. any fix so far?

Nope.I'm using LoliSnatcher instead.

**Comment by onlymash** [comment]
Fixed https://github.com/flexbooru/flexbooru/releases/tag/2.7.0
