### ISSUE TITLE
Gelbooru API change made app stop working

### ISSUE THREAD

**Issue by exentio** [flexbooru/flexbooru#174]
Gelbooru recently had some API changes that broke the app, kinda weird that nobody noticed after 4 days

https://twitter.com/gelbooru/status/1477788287599325184

**Comment by splitfuse** [comment]
I've noticed it and posted it on the Discord already, like 2 days ago. Probably a good idea to open an issue though, as I haven't even seen a sign of acknowledgement from the developers...

**Comment by onlymash** [comment]
Fixed https://github.com/flexbooru/flexbooru/commit/db32554641378041183d0dd40c1d5c28ca9be3eb
