### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by linsui** [flexbooru/flexbooru#175]
Could you please publish this app on F-Droid? Thanks!

**Comment by linsui** [comment]
If you doesn't oppose the inclusion, I can package this app and submit it.

**Comment by licaon-kter** [comment]
Why is this closed ?

**Comment by linsui** [comment]
No response for more than 3 months, I don't think it makes sense to wait forever.

**Comment by licaon-kter** [comment]
Didn't notice the date. :(

But I would not call this as neither opposed nor accepted.

I'd vote to make the MR a "draft" on hold until we get a definitive answer.

**Comment by vvb2060** [comment]
Very good, you make this project no longer open source.

**Comment by linsui** [comment]
What are you talking about? How can I do that?

**Comment by vvb2060** [comment]
Did you forget that you are distributing the cracked version of this app in an official capacity at f-Droid?

**Comment by vvb2060** [comment]
The package name, repo url, author info, etc. are all of this project, but the apk is a cracked version.

**Comment by linsui** [comment]
I do have asked here 5 monthes ago and didn't get any objection. Until now no one contacts me with any objection. And I just make this project no longer open source? How?

**Comment by vvb2060** [comment]
>  I do not intend to crack it 

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10999#note_933145644

> Or I can fork it, which makes no difference.

You didn't fork, you publish app that uses paid features for free under the name of the original project.  If this is not a crack, what is a crack?

**Comment by onlymash** [comment]
The name, icon and package name are all my copyright, if you want to fork please don't use the same

**Comment by linsui** [comment]
I'll remove it since you say no.
