### ISSUE TITLE
Error 403 when try to favorite an image on danbooru

### ISSUE THREAD

**Issue by Atoli** [flexbooru/flexbooru#199]
**Describe the bug**
If login to danbooru with account and try to add an image to favorites it will give an error that says "Code: 403"

**To Reproduce**
1. Add danbooru catalog
2. Login with danbooru account
3. Favorite an image
4. Error 403

**Comment by anpuhach** [comment]
The same, Flexbooru version is 3.1.0.c1293

**Comment by onlymash** [comment]
Danbooru’s API broken

**Comment by Atoli** [comment]
> Danbooru’s API broken

Is it not a flexbooru feature? I tried other app and could favorite posts...but flexbooru has more features.

**Comment by onlymash** [comment]
> 

Report the issue to https://github.com/danbooru/danbooru

**Comment by nonamethanks** [comment]
Reposting this from the danbooru repo: 
Login and Api Key are being sent [here](https://github.com/flexbooru/flexbooru/blob/130469d2d38521c68f295c79ef4be45d85009203/android/src/main/java/onlymash/flexbooru/data/api/DanbooruApi.kt#L52) as POST data. They should instead be sent as basic HTTP authentication or URL parameters.
