### ISSUE TITLE
Logging in to Danbooru account causes Error 401

### ISSUE THREAD

**Issue by MiniFoxx** [flexbooru/flexbooru#205]
No posts will populate on posts, or popular tabs. Pools, Tags, and Artists say error 401 [retry]. Only logging out of the account fixes it.

Android 12
FlexBooru 3.1.1.c1296 

![Screenshot_20221115-191327_Flexbooru](https://user-images.githubusercontent.com/100538933/202051989-8a0203e6-45c8-47a8-8371-45a88250b588.png)

**Comment by MiniFoxx** [comment]
Adding tag blacklists even when not adding account also causes posts to disapp

**Comment by onlymash** [comment]
![Screenshot_20221120-090710_Chrome](https://user-images.githubusercontent.com/5838634/202877929-69dd8776-39e5-477a-986c-d38a3513e262.png)
The blacklist is also part of the tag

**Comment by MiniFoxx** [comment]
I understand how tag blacklisting works. This doesn't address the problem either. _Any_ tag blacklists, even without loading a tag search, automatically clears out the app and makes all posts disappear. I previously had blacklist tags, then on the latest update this 401 issue started happening. 

Don't forget the main issue of this issue is even logging into an account causes the error 401.

**Comment by onlymash** [comment]
Login by your API key is not password

**Comment by MiniFoxx** [comment]
Awesome! That fixed both! Thank you! My password manager was automatically using password and not the API key.
