### ISSUE TITLE
Danbooru video never loads

### ISSUE THREAD

**Issue by antikovt** [flexbooru/flexbooru#237]
Trying to load any video on danbooru just shows an empty player and never loads anything.

1. Go to danbooru 
2. Click on any video

![Screenshot_20240114-114626.png](https://github.com/flexbooru/flexbooru/assets/76940779/5c83538d-4fdc-475f-a080-823f29f83cf4)

 - Device name: Google Pixel 7 Pro 
 - OS version: Android 14
 - App version: 3.2.2.c1361

**Comment by empathist-dot** [comment]
is the app dead at this point? videos don't load. api.rule34.xxx dont load. rule34.paheal gives format unsupported error...
Nothing works

**Comment by antikovt** [comment]
> is the app dead at this point? videos don't load. api.rule34.xxx dont load. rule34.paheal gives format unsupported error...
> Nothing works

Yeahhh, I ended up switching

**Comment by empathist-dot** [comment]
> > is the app dead at this point? videos don't load. api.rule34.xxx dont load. rule34.paheal gives format unsupported error...
> > Nothing works
> 
> Yeahhh, I ended up switching

to what app did you switch?

**Comment by antikovt** [comment]
> > > is the app dead at this point? videos don't load. api.rule34.xxx dont load. rule34.paheal gives format unsupported error...
> > > Nothing works
> > 
> > Yeahhh, I ended up switching
> 
> to what app did you switch?

Boorusama
