### ISSUE TITLE
The tags list of Konachan.com keeps repeating

### ISSUE THREAD

**Issue by sakl2012** [flexbooru/flexbooru#25]
The tags list doesn't work. There are only 10 tags repeating. The number is equal to the page size in setting

**Comment by onlymash** [comment]
![ScreenRecord-2019-03-05-20-57-43_00.gif](https://i.loli.net/2019/03/05/5c7e7309e7925.gif)

**Comment by sakl2012** [comment]
I'm sorry that I didn't provide the screenshot. What I mentioned is another tag list.
![screenshot_20190306-071527](https://user-images.githubusercontent.com/11972321/53844499-daf19380-3fe0-11e9-8106-617be7a6c0f7.jpg)

**Comment by onlymash** [comment]
@sakl2012 
Konachan's API bug
https://konachan.com/tag.json?order=date&page=1
https://konachan.com/tag.json?order=date&page=2
...
You will find every page is the same

**Comment by sakl2012** [comment]
Thanks for your answer. I didn't know this before, because the website works fine. If you are willing to fix this, maybe you can try parsing the result on the webpage. But it's quite an annoying job. Currently, it's enough for me to just set it to 30 labels.

**Comment by onlymash** [comment]
@sakl2012 you can send an email to the website admin to report the bug
