### ISSUE TITLE
Save failed! No Access to the current path

### ISSUE THREAD

**Issue by Kashouryo** [flexbooru/flexbooru#39]
Happend in 0.7.2. When i tried to save a picture, image selection dialog will pop up(that have nothing to do with saving image) instead. After (trying to) selected a folder, that error message will appear.

running Android 6.0

**Comment by Kashouryo** [comment]
Looks like it have something to do with custom save path... In my config, it have some garbage value
content:// something

**Comment by onlymash** [comment]
[Video][[Flexbooru] Show how to save file by Storage Access Framework (SAF)](https://youtu.be/skjil89MV3M)

**Comment by Kashouryo** [comment]
However, it does not work with some Android variations. For example, the EMUI on my Huawei Mate 8 with Android 6.0 does not support this feature. The proposal that I have is to make this feature togglable to support older devices or devices that been heavily modified.

**Comment by Kashouryo** [comment]
Tested on my HUAWEI Mate 9 Pro running Android 7.0 and EMUI and it works fine. So the problem appears only in Android 6.0 with EMUI.

**Comment by neetsaki** [comment]
In Redmi note 4X, the download bottom is no responding. I also try to edit download path In setting (no responding). Anyone know how to solve it?

**Comment by Kashouryo** [comment]
I also have a Redme N4X that running on Android 7.0 with MIUI 9 installed. I will test it tonight.
